### ISSUE TITLE
Associated type scoping

### ISSUE THREAD

**Issue by sgodwincs** [nvzqz/static-assertions-rs#3]
I'm trying to do something similar to the following (using nightly for const fn):

```rust
#![feature(const_fn)]

use std::mem;

pub trait Foo {
    type Type;
}

pub struct Bar<F> {
    foo: F
}

impl<F: Foo> Bar<F> {
    const_assert!(test; mem::size_of::<F::Type>() <= 8);
}

fn main() {}
```

but I get the following error: 

```
: associated type `Type` not found for `F`
  --> src\main.rs:12:40
   |
12 |     const_assert!(test; mem::size_of::<F::Type>() <= 8);
   |                                        ^^^^^^^ associated type `Type` not found
```

I'm assuming this is because of some reduced scoping due to macros, but is there a possible workaround for this? Or is it because the assertions cannot be used in impl blocks directly?

**Comment by nvzqz** [comment]
Try doing `<F as Foo>::Type` instead

**Comment by sgodwincs** [comment]
Still get a similar error:

```
error[E0277]: the trait bound `F: Foo` is not satisfied
  --> src\main.rs:14:40
   |
14 |     const_assert!(test; mem::size_of::<<F as Foo>::Type>() <= 8);
   |                                        ^^^^^^^^^^^^^^^^ the trait `Foo` is not implemented for `F`
```

It doesn't seem to recognize `F` from the scope of the `impl` block

**Comment by sgodwincs** [comment]
Looked into it a bit more. This is actually a bug related to associated constants: https://github.com/rust-lang/rust/issues/42863 so this can be closed.

**Comment by nvzqz** [comment]
Unfortunately there's many features that can't be implemented due to restrictions on `const` language features and their current implementation/availability. On the bright side, once they're resolved, this project will automatically inherit some of those features.
