### ISSUE TITLE
By hygienic; don't assume Sized is in scope

### ISSUE THREAD

**Issue by Kestrer** [nvzqz/static-assertions-rs#37]
The following code:

```rust
use static_assertions::assert_impl_one;

struct Sized;

struct MyType;
trait MyTrait {}

impl MyTrait for MyType {}

assert_impl_one!(MyType: MyTrait);
```

Doesn't compile because `static_assertions` relies on `::core::marker::Sized` being in scope as `Sized`.

**Comment by nvzqz** [comment]
I _thought_ I had hygiene stuff to work out in this. I'll have this fixed in the next release. Thanks!
