### ISSUE TITLE
[Feature Request] assert_eq_type

### ISSUE THREAD

**Issue by tuxzz** [nvzqz/static-assertions-rs#9]
assert_eq_type:
Asserts at compile-time that two generic or non-generic types with any lifetime are equal

**Comment by nvzqz** [comment]
I'm not entirely sure how this would work for generic types. The ways I can think of implementing this would only work for type aliases or verifying that a reference to a concrete type can become a trait object.

**Comment by nvzqz** [comment]
Finally got around to adding [`assert_eq_type!`](https://docs.rs/static_assertions/0.3.2/static_assertions/macro.assert_eq_type.html) and decided to give it a buddy: [`assert_ne_type!`](https://docs.rs/static_assertions/0.3.2/static_assertions/macro.assert_ne_type.html).
